### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by dakoller** [joshbduncan/word-search-generator#10]
After importing the wordsearch-package - without actually using it - I encounter:
```
>>> from typing import Optional, TypedDict
>>> class KeyInfo(TypedDict):
...     start: tuple[int,int]
...     direction: str
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in KeyInfo
TypeError: 'type' object is not subscriptable
>>> 
```

**Comment by joshbduncan** [comment]
Hmmm, what version of Python are you working with?

**Comment by dakoller** [comment]
Python 3.8.9 (default, Apr 13 2022, 08:48:06) 
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin

**Comment by joshbduncan** [comment]
Yeah, the TypedDict type requires Python 3.9. If you are able to update your Python version everything should work fine. This package is tested on Python 3.10.

**Comment by dakoller** [comment]
this did the trick. Thank you!
