### ISSUE TITLE
Max puzzle size is 25, not 30

### ISSUE THREAD

**Issue by dt215git** [joshbduncan/word-search-generator#12]
Docs state max puzzle size is 30, but this isn't consistent with what's in config.py.
```
# puzzle settings
min_puzzle_size = 10
max_puzzle_size = 25
min_puzzle_words = 1
max_puzzle_words = 30
max_fit_tries = 100
```
At least it's an easy fix 😁 
Nice little tool this 👍

**Comment by joshbduncan** [comment]
Hey, thanks for catching that! I wish all fixes were this easy 😬. I've got the docs updated and a new version coming out. Cheers ✌️
