### ISSUE TITLE
Hi anyone knows how we can save the solution as a pdf file?

### ISSUE THREAD

**Issue by tomahocbc** [joshbduncan/word-search-generator#15]
I need to replace puzzle.show() with a something like solution.save()

**Comment by joshbduncan** [comment]
@tomahocbc, I'm working on this for issue #14. I should have a new version released next week and will update here so you are aware. Thanks!

**Comment by joshbduncan** [comment]
@tomahocbc, I've got a working PR #16 that I think provides the functionality you are looking for.

You can call the `save()` method with `solution=True` to have the solution exported within the same file as the puzzle.

```python
p = WordSearch("dog cat pig")
p.save("test.pdf", solution=True)
```

...result in the pdf file linked below. The "solution" is added as a second page with the words highlighted in red just as you get with the `show(solution=True)` method.
[TestWithSolution.pdf](https://github.com/joshbduncan/word-search-generator/files/9500704/TestWithSolution.pdf)

```python
p = WordSearch("dog cat pig")
p.save("test.csv", solution=True)
```

...result in the csv file linked below. The "solution" is added at the bottom of the csv file with only the puzzle words visible. All other characters are represented as a blank space `" "`.
[TestWithSolution.csv](https://github.com/joshbduncan/word-search-generator/files/9500703/TestWithSolution.csv)

Have a look and let me know what you think. Thanks!
