### ISSUE TITLE
Saving as CSV saves as a PDF with CSV extension

### ISSUE THREAD

**Issue by sofiahall** [joshbduncan/word-search-generator#40]
I am trying to export the word search as a csv file using 

p.save(path="puzzle.csv")

but what it gives me is a pdf with the csv extension instead of a csv file. If I rename the file to puzzle.pdf it shows the pdf.

**Comment by joshbduncan** [comment]
You just need to pass the `format="csv"` argument to the method. The format defaults to PDF so if no argument is supplied.

```Python
p.save(path="puzzle.csv", format="csv")
```

This was a breaking changed made a few versions ago and I see that I didn't update the README. I will get that updated today. Sorry for any confusion.

✌️

**Comment by joshbduncan** [comment]
Okay, I updated the [WIKI](https://github.com/joshbduncan/word-search-generator/wiki/Puzzle-Object) to match the actual code.
