### ISSUE TITLE
Solution without random fill characters

### ISSUE THREAD

**Issue by sofiahall** [joshbduncan/word-search-generator#41]
Hi, this really isn't an issue but more of a request for a feature. Would it be possible to show the puzzle after the solution characters without the random fill characters, so just the puzzle with the answers and the other spots with empty spaces?

**Comment by joshbduncan** [comment]
Yeah someone else also requested this so I've already built it in, I just haven't released a new version yet. Are you mainly using the api directly with Python or via the CLI?

**Comment by sofiahall** [comment]
I am using the api directly with python. I'm excited to see it when it is released!

**Comment by joshbduncan** [comment]
I just push a version 3.4.0 which allows the new argument `hide_fillers` to the `show()` method. If set to `True`, the filler character will be hidden and only the actual word characters will be shown. Please note this will negate the `solution=True` argument. 

```python
from word_search_generator import WordSearch

p = WordSearch("cat bat rat mat hat")
p.show(hide_fillers=True)
```

...will produce:

```
---------------------------
        WORD SEARCH        
---------------------------
                           
                           
                           
                      C A T
                           
  M                        
  A                        
  T                        
              R            
                A          
                  T        
    T   B                  
  A     A                  
H       T                  

Find these words: BAT, CAT, HAT, MAT, RAT
* Words can go SE, NE, S, and, E.

Answer Key: BAT S @ (5, 12), CAT E @ (12, 4), HAT NE @ (1, 14), MAT S @ (2, 6), RAT SE @ (8, 9)
```

Hopefully this helps with your use case. I'll update the package on PyPi shortly, so I fresh pip install should get you the new version. Cheers!
