### ISSUE TITLE
change default path word search.exe

### ISSUE THREAD

**Issue by charulix** [joshbduncan/word-search-generator#50]
HI,

I am using python embedded. It is working great on pip install and using python commandline.

What i would like to ask is

The file word-search.exe is in \scripts folder

Running in commandline scripts\word-search -r 10 -s 15 -l 3 works as expected if pip was done in default directory

But if i were to change the python directory to a different or path and so on the word-search.exe stops working and error below is shown

```
E:\python-3.11.5-embed-amd64>scripts\word-search -r 10 -s 15 -l 3
Fatal error in launcher: Unable to create process using '"E:\python-3.11.5-embed-amd64\python.exe"  "E:\python-3.11.5-embed-amd64\scripts\word-search.exe" -r 10 -s 15 -l 3': The system cannot find the file specified.
```

Is there a way we can change path in configuration file etc for word-search.exe to work? So it remains portable? Thanks

**Comment by joshbduncan** [comment]
So, I'm exclusively a Mac user but I did some digging and it seems this is an issue with the Python path on Windows. There are numerous was to work around this and get the proper Python location correctly set in your PATH variable. I've included a few links below that should help. Cheers!

- [Video 1](https://www.youtube.com/watch?v=cxSwtZLiZPM)
- [Video 2](https://www.youtube.com/watch?v=dq9x6z6f8zI)
- [Reddit Link](https://www.reddit.com/r/learnpython/comments/y5biip/fatal_error_in_launcher_unable_to_create_process/)

**Comment by charulix** [comment]
thank you

**Comment by charulix** [comment]
thank you
