### ISSUE TITLE
fpdf2 required version discrepancy in dev requirements

### ISSUE THREAD

**Issue by duck57** [joshbduncan/word-search-generator#53]
requirements.txt requires 2.4.2 while requirements-dev.txt demands 2.5.0

The most recent version is 2.7.5

Should both versions be bumped to 2.7.5?

**Comment by joshbduncan** [comment]
Requirements files are sort of "out of favor" now-a-days. It seems it is becoming more conventional to install requirements via the pyproject.toml file or a packager like hatch/hatchling or poetry. Both requirements files are really just there for anyone who isn't aware of how to install from pyproject.toml. As for bumping the version, I'll have to check their changlog first. Previously, that package has broken something on update.

**Comment by duck57** [comment]
2.4.2 is the version in pyproject.toml, so I'll leave it there.

**Comment by joshbduncan** [comment]
I will check the dependencies for updated before releasing a new version, and update then if need be.

**Comment by joshbduncan** [comment]
@duck57, turns out the new version of fpdf2 did have some breaking changes but I fixed them and updated the rest of the dependencies while I was at it.
