### ISSUE TITLE
Draw a rectangle around the words

### ISSUE THREAD

**Issue by fabiox77** [joshbduncan/word-search-generator#54]
Hi,
First of all thanks for this project. I was wondering if it'd be possible to improve it a little in how it generates the solution. I'd like to have the possibility to create a rectangle or other shapes around the word. Do you think you could add it?

For instance something like the following image
![MetalsWordsearchSolved](https://github.com/joshbduncan/word-search-generator/assets/29281682/c5f6c538-7d4f-416f-80e8-52edbed2fe39)

Thanks

**Comment by joshbduncan** [comment]
It is certainly doable, and honestly, I like the look of the sample you provided. I'm not sure I will be able to get to this soon but I will certainly leave this issue open so that I can tackle it when I have some time. Thanks for the suggestion!

**Comment by joshbduncan** [comment]
Hey @fabiox77, so I finally got around to implementing your suggestion. I may still adjust the colors (they are picked at random for now) so they can also work with the CLI output.

Samples below... Let me know what you think? Cheers!

![sample_highlighting](https://github.com/joshbduncan/word-search-generator/assets/44387852/cf632f79-e684-4c92-bf3c-992be26825c4)

[sample_highlighting.pdf](https://github.com/joshbduncan/word-search-generator/files/14366047/sample_highlighting.pdf)

**Comment by nicolesimon13** [comment]
Shiny! How do we access / use this?

**Comment by joshbduncan** [comment]
You can install directly from git using pip...

```
pip install git+https://github.com/joshbduncan/word-search-generator.git
```
