### ISSUE TITLE
Add an option to generate puzzles with lowercase letters?

### ISSUE THREAD

**Issue by P233** [joshbduncan/word-search-generator#58]
Firstly, thank you so much for developing this project. I've been searching for a word search generator for quite some time.

I understand that using uppercase letters is a tradition, but I plan to use this tool to assist my 7-year-old daughter in learning English as a second language. Lowercase letters would be more suitable for her.

Could you please consider adding an option to generate puzzles with lowercase letters?

Thank you again for your work on this fantastic project!

**Comment by P233** [comment]
Hi @joshbduncan, thank you very much!

1. All letters in the puzzle are in lowercase.
2. Utilize this package directly within Python.

I plan to gather new words from her reading books (e.g., Frog and Toad), create word search puzzles, and engage in play together until she becomes familiar with these words. Afterward, I'll encourage her to start reading the book. This is why I'd like to have all lowercase letters in the puzzle and intend to manage new words by creating a Python file and executing this package within it.

**Comment by joshbduncan** [comment]
Thanks for responding. I'll get this implemented in the next version (coming very soon) and let you know when it is live. Thanks!

**Comment by joshbduncan** [comment]
Ok, I got implemented. It is not officially released yet but you can install it directly from GitHub using the following command...

```
pip install git+https://github.com/joshbduncan/word-search-generator
```

Once installed, you can set the `lowercase=True` argument in the `show` method. The argument also works for the `save` method.

```python
from word_search_generator import WordSearch


p = WordSearch("cat dog ant", size=5)
p.show(lowercase=True)
# or
p.save(format="PDF", solution=True, lowercase=True)
```

Works from the command line (CLI) too...

```
$ word-search cat bat rat -lc -s 5
 -----------
WORD SEARCH
-----------
 a r o t p
 n f y s c
 t r d k a
 u o c o t
 r r u q g

Find these words: ant, cat, dog
* Words can go E, NE, S, and, SE

Answer Key: ant S @ (1, 1), cat S @ (5, 2), dog SE @ (3, 3)
```

**Comment by P233** [comment]
Works like a charm. Thank you so much!

I am not familiar with Python. I didn't realize it would take that much effort. I really appreciate your help!

**Comment by joshbduncan** [comment]
My pleasure!
