### ISSUE TITLE
latest cli version word-search

### ISSUE THREAD

**Issue by charulix** [joshbduncan/word-search-generator#65]
hi,
would like to know where we can get the word-search.exe for command line which have -i for words.txt and lowercase letter as in the 2024 updated wiki 

curreny using version 3.5 from pypi.

**Comment by joshbduncan** [comment]
Hey, the online wiki is for the latest Github version which hasn't been released on Pypi yet (still working on a few new features). You can install the latest version directly from GitHub using the command below.

```
$ pip install git+https://github.com/joshbduncan/word-search-generator
```

**Comment by charulix** [comment]
thank you for the update
