### ISSUE TITLE
palindrome words throw an error

### ISSUE THREAD

**Issue by danewfie** [joshbduncan/word-search-generator#74]
When attempting to use any palindrome like:

`$ word-search eve tenet madam`

it will throw an error:

> ValueError: Use words longer than one-character and without punctuation.

word-search --version: 3.5.1

**Comment by joshbduncan** [comment]
Hey, yes the default generator ignores palindromes as it can cause errors with key coordinates and valid directions. There is a new version (v4.0.0) coming out "soon". The code is basically done, I just need to add some testing for the new features.

One of the new features is custom word validators. You can read a bit about them [here](https://github.com/joshbduncan/word-search-generator/issues/62#issuecomment-1939299610).

If you are not interested in building your own word search game object, you can simply disable the word validators from the CLI.

```
$ word-search eve tenet madam --no-validators
         WORD SEARCH
 ───────────────────────────
 A P T Y C E V X P H Z P K Y
 A M W I T B A W R L X N F Y
 J P S J V E P F M E N T E R
 X Y F C X B H Z A K G E C E
 Z B L O G J A P D D K N W V
 F P J J E I U Q A W F E Q E
 O C D C M X S L M L U T F P
 Y X R A L O I I G B R L Q P
 S R G A P R Y S A D F I G E
 L L S Y E O B A V V W G O Y
 U E R Y D P V U U T N D R O
 I I Z K K R V C W H V G O L
 M L U A Q K Z Y V H L R S W
 Q U C N E Q F I N N B A X Q
 ───────────────────────────
Find words going SE, S, NE, and, E:
EVE, MADAM, TENET

Answer Key: EVE S @ (14, 4), MADAM S @ (9, 3), TENET S @ (12, 3)
```

To pip install the working version directly from GitHub, just use the command below.

```
$ pip install git+https://github.com/joshbduncan/word-search-generator
```

Let me know if you have any questions? Cheers!
