### ISSUE TITLE
Question about hide_key argument

### ISSUE THREAD

**Issue by tazman551** [joshbduncan/word-search-generator#75]
I was looking in the code on Git Hub and saw that, maybe, we could hide the key when writing to a file. The arg is in the Save function, but an error is logged when I try to invoke it. 

TypeError: WordSearch.save() got an unexpected keyword argument 'hide_key'

I could have PIP installed an older version or the GitHub version is not in the pip module yet. Can you confirm that this should work?

I am newer to Python so I am a little shaky with the syntax and how modules are built.

**Comment by joshbduncan** [comment]
Hey, you guessed it! The latest version (v4.0.0) hasn't been released on Pypi yet. To access the new features you can pip install the most recent code directly from GitHub using the command below.

```
pip install git+https://github.com/joshbduncan/word-search-generator
```

Let me know if you have any other questions. I'm here to help!
